version: "3"
services:
  blog-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: blog-api
    ports:
      - "0.0.0.0:7001:7001"
    networks:
      - local-bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
   local-bridge:
     external: true
    
